# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.5
install: pip install -r requirements/dev.txt
services:
  - docker
before_install:
  - docker build -t mrr_website .
  - docker run -d -p 8080:8080  mrr_website
script: sleep 10 && curl -iv  localhost:8080
