sudo: false
language: python
python:
  - 3.5
install: pip install -r requirements/dev.txt
services:
  - docker
before_install:
  - docker build -t registry.heroku.com/$STAGING_APP/web .
  - docker run -d -p 8080:8080 -e PORT=8080  registry.heroku.com/$STAGING_APP/web
after_success:
  - .travis/after_success.sh
branches:
  only:
      - master